## Introduction to Decision Tree algorithm

A Decision Tree algorithm is one of the most popular machine learning algorithms. It uses a tree like a structure and their possible combinations to solve a particular problem. It belongs to the class of supervised learning algorithms where it can be used for both classfication and regression purposes.

A decision tree is a structure that includes a root node, branches, and leaf nodes. Each internal node denotes a test on an attribute, each branch denotes the outcome of a test, and each leaf node holds a class label. The topmost node in the tree is the root node.

We make some assumptions while implementing the Decision-Tree algorithm:
1. At the beginning, the whole training set is considered as the root.
2. Feature values need to be categorical. If the values are continuous then they are discretized prior to building the model.
3. Records are distributed recursively on the basis of attribute values.
4. Order to placing attributes as root or internal node of the tree is done by using some statistical approach.

## Decision Tree Algorithm intuition

The Decision-Tree algorithm is one of the most frequently and widely used supervised ML algorithms that can be used for both classification and regression tasks. The intuition behind the Decision-Tree algorithm is:
1. For each attribute in the data set, the Decision-Tree algorithm forms a node. The most important attribute is placed at $\text{the root node}$
2. For evaluating the task in hand, we start at the root node and we work our way down the tree by following the corresponding node that meets our condition or decision.
3. This process continues until a leaf node is reached. It contains the prediction or the outcome of the Decision Tree.

### Attribute selection measures

The primary challenge in the Decision Tree implementation is to indentify the attributes which we consider as the root node and each level. This process is known as the attributes selection. There are different attributes selection measure to identify the attribute which can be considered as the root node at each level.

There are 2 popular attribute selection measures. They are as follows:
1. $\text{Information gain}$
2. $\text{Gini index}$

While using $\text{Information gain}$ as a criterion, we assume attributes to be categorical ($\text{categorical data}$) and for $\text{Gini Index}$ attributes are assumed to be continuous ($\text{numerical data}$). These attribute selection measures are: 

1. $\text{Entropy}$

Entropy measures the impurity in the given dataset. In Physics and Mathematics, Entropy is referred to as the randomness or uncertainty of a random variable X. In information theory, it refers to the impurity in a group of examples. $\text{Information gain}$ is the decrease in entropy. $\text{Information gain}$ computes the difference between entropy before split and average entropy after split of the dataset based on given attribute values.

$\text{Entropy}$ is represented by the following formula:

$$\text{Entropy} = -\sum_{i=1}^{C}p_i*\log_2(p_i)$$ 

Here, $\text{c}$ is the number of classes and $p_i$ is the probability associated with the $i_{th}$ class. 

Then, 

$$\text{Information Gain} = Entropy_{(parent)} - \sum_{i=1}^{N}(\frac{n_i}{N}*Entropy_{(i)})$$

Example, if the $\text{parent}$ is fruits, and it has 2 childrens (8 $\text{oranges}$ and 2   $\text{apples}$). Then the value of $Entropy_{(child)}$ equal:

$$

The ID3 (Iterative Dichtomiser) Decision Tree algorithm uses $\text{Entropy}$ to calculate information gain. So, by calculating decrease in $\text{entropy measure}$ of each attribute, we can calculate their information gain. The attribute with the highest information gain is chosen as the splitting attribute at the node.

2. $\text{Gini index}$

Another attribute selection measure that $\text{CART}$ uses is the $\text{Gini index}$. It uses the Gini method to create split points.

Gini index can be represented with the following diagram:

$$\text{Gini} = 1 - \sum_{i=1}^{C}(p_i)^{2}$$

Here, again $c$ is the number of classes and $p_i$ is the probability associated with the $i_{th}$ class.

$\text{Gini index}$ says, if we randomly select two items from a population, they must be of the same class and probability for this is 1 if the population is pure. Therefore, if the value of $(p_i)^{2}$ is larger, this attribute is also purer.

### Overfitting in Decision Tree algorithm

Overfitting is a practical problem while building a Decision-Tree model. The problem of overfitting is considered when the algorithm continues to go deeper and deeper to reduce the training-set error but results with an increased test-set error. So, accuracy of prediction for our models goes down. It generally happens when we build many branches due to outliers and irregularities in data.

So, we have two approaches which can be used to avoid it:

1. Pre-Pruning

In $\text{Pre-pruning}$, we stop the tree construction a bit early. We prefer not to split a node if its goodness measure is below a threshold value. But it is difficult to choose an appropriate stopping point.

2. Post-Pruning

In $\text{Post-pruning}$, we go deeper and deeper in the tree to build a complete tree. If the tree shows the overfitting problem, then pruning is done as a post-pruning step. We use the cross-validation data to check the effect of our pruning. Using cross-validation data, we test whether expanding a node with result in improve or not. If it shows an improvement, then we can continue to expand this node, in versa.

### Import Labraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Import Dataset

In [5]:
df = pd.read_csv("C:/Users/ADMIN/Desktop/Ok/ML/Decision-Tree/car_evaluation.csv")
df.shape

(1727, 7)

### Exploratory Data Analysis (EDA)

In [6]:
df.head(5)

   vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [8]:
col_names = ["buying", "maint", "doors", "persons", "lug_boot", "safety", "decision"]

df.columns = [col_names]
df.head()

  buying  maint doors persons lug_boot safety decision
0  vhigh  vhigh     2       2    small    med    unacc
1  vhigh  vhigh     2       2    small   high    unacc
2  vhigh  vhigh     2       2      med    low    unacc
3  vhigh  vhigh     2       2      med    med    unacc
4  vhigh  vhigh     2       2      med   high    unacc

In [12]:
#find the missing percentage of each attribute
for i in df.columns.values:
    missing_value = df[i].isna().sum()
    missing_percentage = (missing_value/len(df[i]))*100
    print(f"Column {i} has: {missing_percentage}% missing values")

Column ('buying',) has: 0.0% missing values
Column ('maint',) has: 0.0% missing values
Column ('doors',) has: 0.0% missing values
Column ('persons',) has: 0.0% missing values
Column ('lug_boot',) has: 0.0% missing values
Column ('safety',) has: 0.0% missing values
Column ('decision',) has: 0.0% missing values

In [13]:
df["decision"].value_counts()

(decision,)
unacc          1209
acc             384
good             69
vgood            65
Name: count, dtype: int64

### Declare feature vector and target variable

In [14]:
X = df.drop("decision", axis = 1)
y = df["decision"]

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_20628\3295007619.py:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  X = df.drop("decision", axis = 1)

In [17]:
#Split data into seperate training and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 42)
X_train.shape, X_test.shape

((1208, 6), (519, 6))

### Feature Engineering

$\text{Feature Engineering}$ is the process of transforming raw data into useful features that help us to understand our model better and increase its predictive power. We will carry out feature engineering on different types of variables

In [19]:
X_train.dtypes

buying      object
maint       object
doors       object
persons     object
lug_boot    object
safety      object
dtype: object

In [20]:
X_train.head()

     buying maint  doors persons lug_boot safety
1177    med   med  5more       4      big   high
585    high  high      3    more    small    med
1551    low   med      3       4      med    med
727    high   med      4    more      big   high
707    high   med      4       2      big    low

In [26]:
#import category encoders
import category_encoders as ce
cate_cols = ["buying", "maint", "doors", "persons", "lug_boot", "safety"]
encoder = ce.OrdinalEncoder(cate_cols)
X_train = encoder.fit_transform(X_train)
X_test = encoder.transform(X_test)

In [27]:
X_train.head()

     buying maint doors persons lug_boot safety
1177      1     1     1       1        1      1
585       2     2     2       2        2      2
1551      3     1     2       1        3      2
727       2     1     3       2        1      1
707       2     1     3       3        1      3

### Decision Tree Classifier with criterion Gini Index

In [34]:
from sklearn.tree import DecisionTreeClassifier
clf_gini = DecisionTreeClassifier(criterion = 'gini', max_depth = 3, random_state = 0)

clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3, random_state=0)

In [35]:
y_pred_gini = clf_gini.predict(X_test)

In [36]:
y_pred_gini

array(['unacc', 'unacc', 'unacc', 'acc', 'unacc', 'acc', 'unacc', 'unacc',
       'acc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'acc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'acc', 'unacc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc',
       'unacc', 'acc', 'unacc', 'unacc', 'acc', 'unacc', 'acc', 'acc',
       'acc', 'acc', 'unacc', 'unacc', 'acc', 'acc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'acc', 'acc', 'unacc',
       'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'acc', 'acc', 'unacc', 'acc', 'unacc', 'acc',
       'acc', 'unacc', 'acc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc',
       'unacc', 'acc', 'unacc', 'unacc', 'acc', 'unacc', 'acc', 'unacc',
       'unacc', 'acc', 'acc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'acc', 'acc', 'unacc', 'unacc', 'acc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'acc', 'acc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'acc', 'unacc', 'acc', 'acc', 'acc', 'unacc',
       'unacc', 'unacc', 'unacc', 'acc', 'acc', 'unacc', 'acc', 'unacc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'acc', 'acc', 'acc',
       'acc', 'unacc', 'acc', 'unacc', 'acc', 'unacc', 'acc', 'acc',
       'unacc', 'acc', 'unacc', 'acc', 'acc', 'acc', 'unacc', 'unacc',
       'acc', 'unacc', 'unacc', 'unacc', 'acc', 'acc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc',
       'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc',
       'unacc', 'acc', 'unacc', 'acc', 'unacc', 'acc', 'acc', 'acc',
       'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'acc', 'acc', 'unacc', 'unacc', 'acc', 'acc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'acc', 'acc', 'unacc', 'acc', 'unacc', 'acc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'acc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'acc', 'unacc',
       'acc', 'acc', 'unacc', 'unacc', 'acc', 'unacc', 'acc', 'acc',
       'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'acc', 'acc', 'acc', 'acc', 'unacc',
       'unacc', 'unacc', 'acc', 'unacc', 'acc', 'acc', 'acc', 'unacc',
       'acc', 'acc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc',
       'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'acc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'acc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'acc', 'unacc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc',
       'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'acc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc',
       'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'acc', 'acc', 'acc',
       'unacc', 'acc', 'acc', 'unacc', 'acc', 'unacc', 'acc', 'unacc',
       'acc', 'unacc', 'unacc', 'acc', 'acc', 'unacc', 'unacc', 'unacc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc',
       'unacc', 'acc', 'acc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'acc', 'unacc', 'acc', 'acc', 'acc', 'unacc', 'unacc',
       'acc', 'unacc', 'acc', 'acc', 'acc', 'unacc', 'unacc', 'acc',
       'acc', 'acc', 'unacc', 'acc', 'acc', 'unacc', 'unacc', 'acc',
       'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc',
       'unacc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc',
       'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'acc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'unacc',
       'unacc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc', 'unacc', 'acc',
       'acc', 'acc', 'unacc', 'unacc', 'acc', 'unacc', 'unacc', 'unacc',
       'unacc', 'acc', 'acc', 'unacc', 'unacc', 'unacc', 'unacc', 'acc'],
      dtype=object)

### Check accuracy score of model

In [37]:
from sklearn.metrics import accuracy_score
print(f"Score: {accuracy_score(y_test,y_pred_gini)}")

Score: 0.815028901734104