In [184]:
import numpy as np
import pandas as pd

In [185]:
pd.set_option('display.max_columns', None)

In [307]:
house_df = pd.read_csv("C:/Users/HELLO/Desktop/Data Science/data/house_prices_data_for_ml/train.csv", index_col = "Id")
test_df = pd.read_csv("C:/Users/HELLO/Desktop/Data Science/data/house_prices_data_for_ml/test.csv")

In [187]:
house_df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [188]:
house_df.dtypes

MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 80, dtype: object

In [189]:
for i in house_df.columns:
    missing_data = house_df[i].isna().sum()
    missing_percent = ((missing_data)/(len(house_df)))*100
    print(f"Column: {i} has {missing_percent}%")

Column: MSSubClass has 0.0%
Column: MSZoning has 0.0%
Column: LotFrontage has 17.73972602739726%
Column: LotArea has 0.0%
Column: Street has 0.0%
Column: Alley has 93.76712328767123%
Column: LotShape has 0.0%
Column: LandContour has 0.0%
Column: Utilities has 0.0%
Column: LotConfig has 0.0%
Column: LandSlope has 0.0%
Column: Neighborhood has 0.0%
Column: Condition1 has 0.0%
Column: Condition2 has 0.0%
Column: BldgType has 0.0%
Column: HouseStyle has 0.0%
Column: OverallQual has 0.0%
Column: OverallCond has 0.0%
Column: YearBuilt has 0.0%
Column: YearRemodAdd has 0.0%
Column: RoofStyle has 0.0%
Column: RoofMatl has 0.0%
Column: Exterior1st has 0.0%
Column: Exterior2nd has 0.0%
Column: MasVnrType has 59.726027397260275%
Column: MasVnrArea has 0.547945205479452%
Column: ExterQual has 0.0%
Column: ExterCond has 0.0%
Column: Foundation has 0.0%
Column: BsmtQual has 2.5342465753424657%
Column: BsmtCond has 2.5342465753424657%
Column: BsmtExposure has 2.6027397260273974%
Column: BsmtFinType1 has 2.5342465753424657%
Column: BsmtFinSF1 has 0.0%
Column: BsmtFinType2 has 2.6027397260273974%
Column: BsmtFinSF2 has 0.0%
Column: BsmtUnfSF has 0.0%
Column: TotalBsmtSF has 0.0%
Column: Heating has 0.0%
Column: HeatingQC has 0.0%
Column: CentralAir has 0.0%
Column: Electrical has 0.0684931506849315%
Column: 1stFlrSF has 0.0%
Column: 2ndFlrSF has 0.0%
Column: LowQualFinSF has 0.0%
Column: GrLivArea has 0.0%
Column: BsmtFullBath has 0.0%
Column: BsmtHalfBath has 0.0%
Column: FullBath has 0.0%
Column: HalfBath has 0.0%
Column: BedroomAbvGr has 0.0%
Column: KitchenAbvGr has 0.0%
Column: KitchenQual has 0.0%
Column: TotRmsAbvGrd has 0.0%
Column: Functional has 0.0%
Column: Fireplaces has 0.0%
Column: FireplaceQu has 47.26027397260274%
Column: GarageType has 5.5479452054794525%
Column: GarageYrBlt has 5.5479452054794525%
Column: GarageFinish has 5.5479452054794525%
Column: GarageCars has 0.0%
Column: GarageArea has 0.0%
Column: GarageQual has 5.5479452054794525%
Column: GarageCond has 5.5479452054794525%
Column: PavedDrive has 0.0%
Column: WoodDeckSF has 0.0%
Column: OpenPorchSF has 0.0%
Column: EnclosedPorch has 0.0%
Column: 3SsnPorch has 0.0%
Column: ScreenPorch has 0.0%
Column: PoolArea has 0.0%
Column: PoolQC has 99.52054794520548%
Column: Fence has 80.75342465753424%
Column: MiscFeature has 96.30136986301369%
Column: MiscVal has 0.0%
Column: MoSold has 0.0%
Column: YrSold has 0.0%
Column: SaleType has 0.0%
Column: SaleCondition has 0.0%
Column: SalePrice has 0.0%

In [268]:
x = house_df.iloc[:,:-1].values
y = house_df.iloc[:,-1].values

In [285]:
#Split numeric columns and string columns
numeric_cols = house_df.select_dtypes(include = ["int64","float64"]).columns
categorical_cols = house_df.select_dtypes(include = ["object"]).columns
numeric_cols = numeric_cols[:-1]

In [286]:
#Processing NaN in numeric columns
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
house_df[numeric_cols] = imputer.fit_transform(house_df[numeric_cols])
test_df[numeric_cols] = imputer.transform(test_df[numeric_cols])

In [193]:
#house_df.head()

In [288]:
features = numeric_cols

In [289]:
x = house_df[features]

In [290]:
y = house_df.iloc[:,-1]

In [274]:
x.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,60.0,65.0,8450.0,7.0,5.0,2003.0,2003.0,196.0,706.0,0.0,150.0,856.0,856.0,854.0,0.0,1710.0,1.0,0.0,2.0,1.0,3.0,1.0,8.0,0.0,2003.0,2.0,548.0,0.0,61.0,0.0,0.0,0.0,0.0,0.0,2.0,2008.0
2,20.0,80.0,9600.0,6.0,8.0,1976.0,1976.0,0.0,978.0,0.0,284.0,1262.0,1262.0,0.0,0.0,1262.0,0.0,1.0,2.0,0.0,3.0,1.0,6.0,1.0,1976.0,2.0,460.0,298.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,2007.0
3,60.0,68.0,11250.0,7.0,5.0,2001.0,2002.0,162.0,486.0,0.0,434.0,920.0,920.0,866.0,0.0,1786.0,1.0,0.0,2.0,1.0,3.0,1.0,6.0,1.0,2001.0,2.0,608.0,0.0,42.0,0.0,0.0,0.0,0.0,0.0,9.0,2008.0
4,70.0,60.0,9550.0,7.0,5.0,1915.0,1970.0,0.0,216.0,0.0,540.0,756.0,961.0,756.0,0.0,1717.0,1.0,0.0,1.0,0.0,3.0,1.0,7.0,1.0,1998.0,3.0,642.0,0.0,35.0,272.0,0.0,0.0,0.0,0.0,2.0,2006.0
5,60.0,84.0,14260.0,8.0,5.0,2000.0,2000.0,350.0,655.0,0.0,490.0,1145.0,1145.0,1053.0,0.0,2198.0,1.0,0.0,2.0,1.0,4.0,1.0,9.0,1.0,2000.0,3.0,836.0,192.0,84.0,0.0,0.0,0.0,0.0,0.0,12.0,2008.0

In [233]:
x.shape

(1460, 36)

In [234]:
y.head()

Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

In [275]:
from sklearn.model_selection import train_test_split
x_train, x_valid, y_train, y_valid = train_test_split(x,y,train_size = 0.8, test_size = 0.2, random_state = 0)

In [276]:
x_train.shape

(1168, 36)

In [237]:
x_valid

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
530,20,NaN,32668,6,3,1957,1975,NaN,1219,0,816,2035,2515,0,0,2515,1,0,3,0,4,2,9,2,1975.0,2,484,0,0,200,0,0,0,0,3,2007
492,50,79.0,9490,6,7,1941,1950,0.0,403,165,238,806,958,620,0,1578,1,0,1,0,3,1,5,2,1941.0,1,240,0,0,32,0,0,0,0,8,2006
460,50,NaN,7015,5,4,1950,1950,161.0,185,0,524,709,979,224,0,1203,1,0,1,0,3,1,5,1,1950.0,1,352,0,0,248,0,0,0,0,7,2009
280,60,83.0,10005,7,5,1977,1977,299.0,392,0,768,1160,1156,866,0,2022,0,0,2,1,4,1,8,1,1977.0,2,505,288,117,0,0,0,0,0,3,2008
656,160,21.0,1680,6,5,1971,1971,381.0,0,0,525,525,525,567,0,1092,0,0,1,1,3,1,6,0,1971.0,1,264,0,0,0,0,0,0,0,3,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,120,32.0,10846,8,5,1993,1993,0.0,1619,0,100,1719,1719,0,0,1719,2,0,1,1,1,1,6,2,1993.0,2,473,122,30,0,0,0,0,0,5,2008
441,20,105.0,15431,10,5,2008,2008,200.0,1767,539,788,3094,2402,0,0,2402,1,0,2,0,2,1,10,2,2008.0,3,672,0,72,0,0,170,0,0,4,2009
1388,50,60.0,8520,6,7,1916,1950,0.0,168,546,0,714,1664,862,0,2526,0,0,2,0,5,1,10,1,1916.0,1,216,88,15,0,0,0,0,0,8,2007
1324,30,50.0,5330,4,7,1940,1950,0.0,280,0,140,420,708,0,0,708,0,0,1,0,2,1,5,0,NaN,0,0,164,0,0,0,0,0,0,12,2009
62,75,60.0,7200,5,7,1920,1996,0.0,0,0,530,530,581,530,0,1111,0,0,1,0,3,1,6,0,1935.0,1,288,0,0,144,0,0,0,0,3,2007

In [238]:
x_valid.shape

(292, 36)

In [277]:
from sklearn.tree import DecisionTreeRegressor
dt_model = DecisionTreeRegressor(random_state = 1)

In [278]:
dt_model.fit(x_train,y_train)

DecisionTreeRegressor(random_state=1)

In [241]:
dt_model.predict(x_valid)

array([240000., 113000., 143500., 205000.,  94500., 108480., 255000.,
       120000., 184750., 144152., 202500., 149000., 214000., 119900.,
       143000., 153000., 254900., 119000., 155000., 167500., 127000.,
       144000., 115000., 178000., 165000., 233230., 168500.,  75500.,
       315000., 123500., 124000., 185000., 155000., 339750., 410000.,
       170000., 328900., 125000., 236000., 369900., 244000.,  89500.,
       176485., 275000., 348000., 161500., 129000., 147000., 230000.,
       111000., 446261., 149900., 185000.,  60000., 220000., 100000.,
       135500., 283463., 155000.,  76000., 148500., 138500., 143000.,
       145000., 217000., 129500., 120000., 188000., 117000., 241000.,
       162000., 113000.,  82000., 202500.,  84000., 244600., 140000.,
       105500., 274725., 179900., 137000., 144000., 108480., 156000.,
       169000., 210000., 107000., 202500., 177500., 124500., 207500.,
       150900., 207500., 254900., 159895., 143000., 204000., 274970.,
       100000., 135000., 311872., 252678., 116000., 148500.,  76000.,
       267000., 147000., 103200., 178000., 128000., 107500., 155000.,
       214500., 119000., 155000., 148500., 325000., 133700., 177000.,
       252000., 187500., 164700., 146000., 200000., 214000., 250580.,
       380000., 176000., 165000., 170000., 246578., 195400., 190000.,
       162000., 100000., 240000., 113000., 196000., 100000., 187000.,
       147000., 148000., 274970., 152000., 145000., 204000., 202500.,
       134500., 266000., 246578., 188000., 374000., 315500., 175000.,
       212000., 226000., 103000., 212000.,  84500., 164000., 120500.,
       142000., 195400., 102000., 232600., 130000., 135500., 315750.,
       190000., 178000., 194000., 148500., 181000., 157000., 143250.,
       106500., 126175., 259500.,  78000., 155000., 301500., 226000.,
       114500., 297000., 141000., 180500., 106500., 195400., 159895.,
       136500., 140000., 179900., 201000., 134900., 110000., 147000.,
        39300., 130500., 158000., 123000., 132000., 184100.,  76000.,
        84500., 135900., 172000., 143000., 446261., 275000.,  58500.,
       155000., 278000.,  82000., 118500., 326000., 274970., 226000.,
       226000., 232600.,  86000., 226000., 189000., 135000., 127000.,
       171750., 315750., 350000., 230000., 130500., 167000.,  93500.,
       184000.,  97000., 145000., 199900.,  89500., 135000., 129000.,
        90000., 175000., 123500., 274970., 231500., 213500., 165000.,
       184100., 180000., 183000., 102000., 179600., 162000., 252000.,
        98000., 625000., 202500., 194500.,  92000., 234000., 402000.,
       184750., 220000., 140000., 124500.,  64500., 325000., 395192.,
       369900.,  80000., 311500., 318000., 137500., 197000., 138000.,
       189000., 128000., 236000., 220000., 174500., 215000., 111000.,
       123000., 360000., 187000., 148000., 195400., 160000., 113000.,
       297000., 466500., 117500.,  86000.,  96500.])

In [242]:
y_predis = dt_model.predict(x_valid)

In [207]:
#y_predis

In [243]:
pd.DataFrame({"y": y_valid, "y_predis": y_predis})

           y  y_predis
Id
530   200624  240000.0
492   133000  113000.0
460   110000  143500.0
280   192000  205000.0
656    88000   94500.0
...      ...       ...
327   324000  297000.0
441   555000  466500.0
1388  136000  117500.0
1324   82500   86000.0
62    101000   96500.0

[292 rows x 2 columns]

In [244]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
rf_model = RandomForestRegressor(random_state = 1)
rf_model.fit(x_train,y_train)

RandomForestRegressor(random_state=1)

In [245]:
rf_val_predis = rf_model.predict(x_valid)

In [246]:
rf_val_predis[:5]

array([199980.5 , 151593.37, 109438.76, 230036.99,  86584.69])

In [247]:
test_df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,CBlock,TA,TA,No,Rec,468.0,LwQ,144.0,270.0,882.0,GasA,TA,Y,SBrkr,896,0,0,896,0.0,0.0,1,0,2,1,TA,5,Typ,0,NaN,Attchd,1961.0,Unf,1.0,730.0,TA,TA,Y,140,0,0,0,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,108.0,TA,TA,CBlock,TA,TA,No,ALQ,923.0,Unf,0.0,406.0,1329.0,GasA,TA,Y,SBrkr,1329,0,0,1329,0.0,0.0,1,1,3,1,Gd,6,Typ,0,NaN,Attchd,1958.0,Unf,1.0,312.0,TA,TA,Y,393,36,0,0,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,5,5,1997,1998,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,PConc,Gd,TA,No,GLQ,791.0,Unf,0.0,137.0,928.0,GasA,Gd,Y,SBrkr,928,701,0,1629,0.0,0.0,2,1,3,1,TA,6,Typ,1,TA,Attchd,1997.0,Fin,2.0,482.0,TA,TA,Y,212,34,0,0,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,6,1998,1998,Gable,CompShg,VinylSd,VinylSd,BrkFace,20.0,TA,TA,PConc,TA,TA,No,GLQ,602.0,Unf,0.0,324.0,926.0,GasA,Ex,Y,SBrkr,926,678,0,1604,0.0,0.0,2,1,3,1,Gd,7,Typ,1,Gd,Attchd,1998.0,Fin,2.0,470.0,TA,TA,Y,360,36,0,0,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,Inside,Gtl,StoneBr,Norm,Norm,TwnhsE,1Story,8,5,1992,1992,Gable,CompShg,HdBoard,HdBoard,NaN,0.0,Gd,TA,PConc,Gd,TA,No,ALQ,263.0,Unf,0.0,1017.0,1280.0,GasA,Ex,Y,SBrkr,1280,0,0,1280,0.0,0.0,2,0,2,1,Gd,5,Typ,0,NaN,Attchd,1992.0,RFn,2.0,506.0,TA,TA,Y,0,82,0,0,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [308]:
x_test = test_df[features]
x_test

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,270.0,882.0,896,0,0,896,0.0,0.0,1,0,2,1,5,0,1961.0,1.0,730.0,140,0,0,0,120,0,0,6,2010
1,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,406.0,1329.0,1329,0,0,1329,0.0,0.0,1,1,3,1,6,0,1958.0,1.0,312.0,393,36,0,0,0,0,12500,6,2010
2,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,137.0,928.0,928,701,0,1629,0.0,0.0,2,1,3,1,6,1,1997.0,2.0,482.0,212,34,0,0,0,0,0,3,2010
3,60,78.0,9978,6,6,1998,1998,20.0,602.0,0.0,324.0,926.0,926,678,0,1604,0.0,0.0,2,1,3,1,7,1,1998.0,2.0,470.0,360,36,0,0,0,0,0,6,2010
4,120,43.0,5005,8,5,1992,1992,0.0,263.0,0.0,1017.0,1280.0,1280,0,0,1280,0.0,0.0,2,0,2,1,5,0,1992.0,2.0,506.0,0,82,0,0,144,0,0,1,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,160,21.0,1936,4,7,1970,1970,0.0,0.0,0.0,546.0,546.0,546,546,0,1092,0.0,0.0,1,1,3,1,5,0,NaN,0.0,0.0,0,0,0,0,0,0,0,6,2006
1455,160,21.0,1894,4,5,1970,1970,0.0,252.0,0.0,294.0,546.0,546,546,0,1092,0.0,0.0,1,1,3,1,6,0,1970.0,1.0,286.0,0,24,0,0,0,0,0,4,2006
1456,20,160.0,20000,5,7,1960,1996,0.0,1224.0,0.0,0.0,1224.0,1224,0,0,1224,1.0,0.0,1,0,4,1,7,1,1960.0,2.0,576.0,474,0,0,0,0,0,0,9,2006
1457,85,62.0,10441,5,5,1992,1992,0.0,337.0,0.0,575.0,912.0,970,0,0,970,0.0,1.0,1,0,3,1,6,0,NaN,0.0,0.0,80,32,0,0,0,0,700,7,2006
1458,60,74.0,9627,7,5,1993,1994,94.0,758.0,0.0,238.0,996.0,996,1004,0,2000,0.0,0.0,2,1,3,1,9,1,1993.0,3.0,650.0,190,48,0,0,0,0,0,11,2006

In [294]:
y_answer = dt_model.predict(x_test)

In [310]:
pd.DataFrame({"Id": test_df["Id"], "SalePrice": y_answer})
#len(test_df["Id"])

        Id  SalePrice
0     1461   127500.0
1     1462   170000.0
2     1463   200000.0
3     1464   217000.0
4     1465   180000.0
...    ...        ...
1454  2915    75000.0
1455  2916    75000.0
1456  2917   143000.0
1457  2918    93500.0
1458  2919   219210.0

[1459 rows x 2 columns]

In [328]:
answer = pd.DataFrame({"Id": test_df["Id"], "SalePrice": y_answer})
answer

        Id  SalePrice
0     1461   127500.0
1     1462   170000.0
2     1463   200000.0
3     1464   217000.0
4     1465   180000.0
...    ...        ...
1454  2915    75000.0
1455  2916    75000.0
1456  2917   143000.0
1457  2918    93500.0
1458  2919   219210.0

[1459 rows x 2 columns]

In [329]:
type(answer)

pandas.core.frame.DataFrame

In [334]:
answer.head()

     Id  SalePrice
0  1461   127500.0
1  1462   170000.0
2  1463   200000.0
3  1464   217000.0
4  1465   180000.0

In [336]:
answer.to_csv("answer_final_1.csv", index = False)