In [1]:
import numpy as np
import pandas as pd

In [7]:
house_df = pd.read_csv("C:/Users/HELLO/Desktop/Data Science/data/house_prices_data_for_ml/train.csv", index_col = "Id")

In [8]:
house_df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [43]:
features = ["MSSubClass", "LotFrontage", "LotArea", "PoolArea", "MiscVal", "MoSold", "YrSold", "YearBuilt", "1stFlrSF", "2ndFlrSF", "FullBath", "TotRmsAbvGrd"]

In [44]:
x = house_df[features]

In [16]:
y = house_df.iloc[:,-1]

In [45]:
x.head()

,MSSubClass,LotFrontage,LotArea,PoolArea,MiscVal,MoSold,YrSold,YearBuilt,1stFlrSF,2ndFlrSF,FullBath,TotRmsAbvGrd
Id,,,,,,,,,,,,
1,60,65.0,8450,0,0,2,2008,2003,856,854,2,8
2,20,80.0,9600,0,0,5,2007,1976,1262,0,2,6
3,60,68.0,11250,0,0,9,2008,2001,920,866,2,6
4,70,60.0,9550,0,0,2,2006,1915,961,756,1,7
5,60,84.0,14260,0,0,12,2008,2000,1145,1053,2,9

In [14]:
y.head()

Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

In [46]:
from sklearn.model_selection import train_test_split
x_train, x_valid, y_train, y_valid = train_test_split(x,y,train_size = 0.8, test_size = 0.2, random_state = 0)

In [47]:
x_train.shape

(1168, 12)

In [48]:
x_valid.shape

(292, 12)

In [49]:
from sklearn.tree import DecisionTreeRegressor
dt_model = DecisionTreeRegressor(random_state = 1)

In [50]:
dt_model.fit(x_train,y_train)

DecisionTreeRegressor(random_state=1)

In [52]:
dt_model.predict(x_valid)

array([257500., 152000., 120500., 205000.,  75000., 102000., 244600.,
       119500., 625000., 171900., 202500., 135000., 214000., 135500.,
       109900., 123000., 235000., 126000., 154000., 128000.,  97500.,
       145150., 146000., 185000., 146500., 130000., 195000.,  92000.,
       315000., 115000., 145000., 168000., 145000., 337000., 394617.,
       176000., 217000., 129000., 222500., 341000., 278000., 135000.,
       176000., 372402., 333168., 125000., 100000., 111250., 130500.,
       130000., 354000., 140000., 196000.,  73000., 278000., 129000.,
       109000., 226700., 159000.,  79000., 155000., 109500., 155000.,
       172500., 222000., 165500., 115000., 212000.,  88000., 227000.,
       183200., 127000., 139000., 179600., 128900., 240000., 150000.,
       113000., 354000., 179900., 132500., 130250., 157500., 126000.,
       197000., 194700.,  91500., 197000., 198900., 159500., 188000.,
       184000., 173000., 254900., 202500., 129500., 208900., 140200.,
       129000., 104900., 369900., 192140., 136500., 174500.,  80000.,
       341000., 177000., 115000., 178000., 119500.,  72500., 129500.,
       185000.,  94000., 176000., 113000., 466500., 129000., 185000.,
       213500., 157000., 176000.,  80000., 185000., 221500., 246578.,
       372402., 176000., 197000., 218000., 173000., 250580., 206900.,
       175500., 129900., 224900., 140000., 165000., 110000., 179000.,
       144000., 140000., 242000., 147000., 178400., 174000., 244600.,
        80000., 328900., 259000., 139000., 328900., 372402., 207500.,
       128000., 200000., 102000., 173000., 157000., 168500., 129000.,
       157900., 186500., 132500., 264132., 140200., 166000., 328000.,
       194700., 172400., 170000., 146000., 230000., 112000., 145000.,
        79000., 127000., 256000., 113000., 162500., 175500., 235000.,
       128000., 236500., 128500., 180500.,  83000., 185000., 202500.,
       140000., 147000., 153500., 201000., 136500., 102000., 129900.,
        75500., 150000., 169500., 125000., 150750., 190000.,  86000.,
       147000., 189000., 200000., 131400., 305000., 326000.,  58500.,
       155000., 278000.,  93500.,  79000., 268000., 277000., 196000.,
       315000., 285000.,  86000., 175500., 218000., 140200., 129900.,
       234000., 214000., 165000., 257500., 127000., 174000., 119000.,
        78000., 138500., 126000., 240000., 137500., 113000., 144900.,
       129000., 115000., 129500., 178000., 231500., 222500., 175500.,
        93500., 118911., 183000., 120500., 165000., 136500., 275000.,
       103000., 361919., 198900., 200000., 105000., 192500., 184750.,
       582933., 179400., 113000., 160000., 105000., 440000., 395192.,
       155000.,  60000., 175000., 248328., 152000., 151400., 159434.,
       197900., 118500., 214900., 241000., 180500., 215000., 104900.,
       129900., 440000., 155000., 143000., 196000., 237500., 113000.,
       260400., 451950., 107500.,  76000.,  75000.])

In [53]:
y_predis = dt_model.predict(x_valid.head())

In [54]:
y_predis

array([257500., 152000., 120500., 205000.,  75000.])

In [55]:
pd.DataFrame({"y": y_valid.head(), "y_predis": y_predis})

          y  y_predis
Id
530  200624  257500.0
492  133000  152000.0
460  110000  120500.0
280  192000  205000.0
656   88000   75000.0

In [56]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
rf_model = RandomForestRegressor(random_state = 1)
rf_model.fit(x_train,y_train)

RandomForestRegressor(random_state=1)

In [57]:
rf_val_predis = rf_model.predict(x_valid)

In [58]:
rf_val_predis[:5]

array([267542.  , 153682.12, 118304.58, 193533.  ,  96541.  ])

In [62]:
x_train.head()
rf_model.predict([[25, 100.0, 15000, 1, 0, 9, 2022, 2015, 1000, 500, 5, 9]])

C:\Users\HELLO\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([209071.49])