In [337]:
import numpy as np
import pandas as pd

In [338]:
pd.set_option('display.max_columns', None)

In [466]:
house_df = pd.read_csv("C:/Users/HELLO/Desktop/Data Science/data/house_prices_data_for_ml/train.csv", index_col = "Id")
test_df = pd.read_csv("C:/Users/HELLO/Desktop/Data Science/data/house_prices_data_for_ml/test.csv")

In [467]:
house_df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [506]:
house_df.shape

(1460, 80)

In [468]:
house_df.dtypes

MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 80, dtype: object

In [469]:
for i in house_df.columns:
    missing_data = house_df[i].isna().sum()
    missing_percent = ((missing_data)/(len(house_df)))*100
    print(f"Column: {i} has {missing_percent}%")

Column: MSSubClass has 0.0%
Column: MSZoning has 0.0%
Column: LotFrontage has 17.73972602739726%
Column: LotArea has 0.0%
Column: Street has 0.0%
Column: Alley has 93.76712328767123%
Column: LotShape has 0.0%
Column: LandContour has 0.0%
Column: Utilities has 0.0%
Column: LotConfig has 0.0%
Column: LandSlope has 0.0%
Column: Neighborhood has 0.0%
Column: Condition1 has 0.0%
Column: Condition2 has 0.0%
Column: BldgType has 0.0%
Column: HouseStyle has 0.0%
Column: OverallQual has 0.0%
Column: OverallCond has 0.0%
Column: YearBuilt has 0.0%
Column: YearRemodAdd has 0.0%
Column: RoofStyle has 0.0%
Column: RoofMatl has 0.0%
Column: Exterior1st has 0.0%
Column: Exterior2nd has 0.0%
Column: MasVnrType has 59.726027397260275%
Column: MasVnrArea has 0.547945205479452%
Column: ExterQual has 0.0%
Column: ExterCond has 0.0%
Column: Foundation has 0.0%
Column: BsmtQual has 2.5342465753424657%
Column: BsmtCond has 2.5342465753424657%
Column: BsmtExposure has 2.6027397260273974%
Column: BsmtFinType1 has 2.5342465753424657%
Column: BsmtFinSF1 has 0.0%
Column: BsmtFinType2 has 2.6027397260273974%
Column: BsmtFinSF2 has 0.0%
Column: BsmtUnfSF has 0.0%
Column: TotalBsmtSF has 0.0%
Column: Heating has 0.0%
Column: HeatingQC has 0.0%
Column: CentralAir has 0.0%
Column: Electrical has 0.0684931506849315%
Column: 1stFlrSF has 0.0%
Column: 2ndFlrSF has 0.0%
Column: LowQualFinSF has 0.0%
Column: GrLivArea has 0.0%
Column: BsmtFullBath has 0.0%
Column: BsmtHalfBath has 0.0%
Column: FullBath has 0.0%
Column: HalfBath has 0.0%
Column: BedroomAbvGr has 0.0%
Column: KitchenAbvGr has 0.0%
Column: KitchenQual has 0.0%
Column: TotRmsAbvGrd has 0.0%
Column: Functional has 0.0%
Column: Fireplaces has 0.0%
Column: FireplaceQu has 47.26027397260274%
Column: GarageType has 5.5479452054794525%
Column: GarageYrBlt has 5.5479452054794525%
Column: GarageFinish has 5.5479452054794525%
Column: GarageCars has 0.0%
Column: GarageArea has 0.0%
Column: GarageQual has 5.5479452054794525%
Column: GarageCond has 5.5479452054794525%
Column: PavedDrive has 0.0%
Column: WoodDeckSF has 0.0%
Column: OpenPorchSF has 0.0%
Column: EnclosedPorch has 0.0%
Column: 3SsnPorch has 0.0%
Column: ScreenPorch has 0.0%
Column: PoolArea has 0.0%
Column: PoolQC has 99.52054794520548%
Column: Fence has 80.75342465753424%
Column: MiscFeature has 96.30136986301369%
Column: MiscVal has 0.0%
Column: MoSold has 0.0%
Column: YrSold has 0.0%
Column: SaleType has 0.0%
Column: SaleCondition has 0.0%
Column: SalePrice has 0.0%

In [470]:
x = house_df.iloc[:,:-1].values
#x = pd.DataFrame(x)
y = house_df.iloc[:,-1].values
x

array([[60, 'RL', 65.0, ..., 2008, 'WD', 'Normal'],
       [20, 'RL', 80.0, ..., 2007, 'WD', 'Normal'],
       [60, 'RL', 68.0, ..., 2008, 'WD', 'Normal'],
       ...,
       [70, 'RL', 66.0, ..., 2010, 'WD', 'Normal'],
       [20, 'RL', 68.0, ..., 2010, 'WD', 'Normal'],
       [20, 'RL', 75.0, ..., 2008, 'WD', 'Normal']],
      shape=(1460, 79), dtype=object)

In [471]:
#Split numeric columns and string columns
numeric_cols = house_df.select_dtypes(include = ["int64","float64"]).columns
categorical_cols = house_df.select_dtypes(include = ["object"]).columns
test_categorical_cols = test_df.select_dtypes(include = ["object"]).columns
numeric_cols = numeric_cols[:-1]

In [472]:
#Processing NaN in numeric columns
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
house_df[numeric_cols] = imputer.fit_transform(house_df[numeric_cols])
test_df[numeric_cols] = imputer.transform(test_df[numeric_cols])

In [473]:
categorical_cols

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')

In [474]:
#categorical_cols
test_categorical_cols

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')

In [423]:
house_df.shape
#test_df.shape

(1460, 80)

In [507]:
#Processing NaN in categorical columns
from sklearn.compose import ColumnTransformer
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder

house_ex_price_df = house_df.drop(columns = "SalePrice")

ct = ColumnTransformer(transformers = [("encoder", OneHotEncoder(sparse_output=False, handle_unknown = 'ignore'), categorical_cols)], remainder = "passthrough")
#house_df[categorical_cols] = ct.fit_transform(house_df[categorical_cols])
encoded_array = ct.fit_transform(house_ex_price_df)
encoded_cols = ct.get_feature_names_out()

test_array = ct.transform(test_df)

#encoded_cols
categorical_df = pd.DataFrame(encoded_array, columns = encoded_cols, index = house_df.index)
test_categorical_df = pd.DataFrame(test_array, columns = encoded_cols, index = test_df.index)
#categorical_df
numerical_df = house_ex_price_df.drop(columns = categorical_cols)
test_numerical_df = test_df.drop(columns = categorical_cols)

house_new_df = pd.concat([numerical_df, categorical_df], axis = 1)
test_new_df = pd.concat([test_numerical_df, test_categorical_df], axis = 1)

#ct
#house_ex_price_df.head()
house_new_df["SalePrice"] = house_df["SalePrice"]
house_new_df["SalePrice"] = house_new_df.pop("SalePrice")
house_new_df.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,encoder__MSZoning_C (all),encoder__MSZoning_FV,encoder__MSZoning_RH,encoder__MSZoning_RL,encoder__MSZoning_RM,encoder__Street_Grvl,encoder__Street_Pave,encoder__Alley_Grvl,encoder__Alley_Pave,encoder__Alley_nan,encoder__LotShape_IR1,encoder__LotShape_IR2,encoder__LotShape_IR3,encoder__LotShape_Reg,encoder__LandContour_Bnk,encoder__LandContour_HLS,encoder__LandContour_Low,encoder__LandContour_Lvl,encoder__Utilities_AllPub,encoder__Utilities_NoSeWa,encoder__LotConfig_Corner,encoder__LotConfig_CulDSac,encoder__LotConfig_FR2,encoder__LotConfig_FR3,encoder__LotConfig_Inside,encoder__LandSlope_Gtl,encoder__LandSlope_Mod,encoder__LandSlope_Sev,encoder__Neighborhood_Blmngtn,encoder__Neighborhood_Blueste,encoder__Neighborhood_BrDale,encoder__Neighborhood_BrkSide,encoder__Neighborhood_ClearCr,encoder__Neighborhood_CollgCr,encoder__Neighborhood_Crawfor,encoder__Neighborhood_Edwards,encoder__Neighborhood_Gilbert,encoder__Neighborhood_IDOTRR,encoder__Neighborhood_MeadowV,encoder__Neighborhood_Mitchel,encoder__Neighborhood_NAmes,encoder__Neighborhood_NPkVill,encoder__Neighborhood_NWAmes,encoder__Neighborhood_NoRidge,encoder__Neighborhood_NridgHt,encoder__Neighborhood_OldTown,encoder__Neighborhood_SWISU,encoder__Neighborhood_Sawyer,encoder__Neighborhood_SawyerW,encoder__Neighborhood_Somerst,encoder__Neighborhood_StoneBr,encoder__Neighborhood_Timber,encoder__Neighborhood_Veenker,encoder__Condition1_Artery,encoder__Condition1_Feedr,encoder__Condition1_Norm,encoder__Condition1_PosA,encoder__Condition1_PosN,encoder__Condition1_RRAe,encoder__Condition1_RRAn,encoder__Condition1_RRNe,encoder__Condition1_RRNn,encoder__Condition2_Artery,encoder__Condition2_Feedr,encoder__Condition2_Norm,encoder__Condition2_PosA,encoder__Condition2_PosN,encoder__Condition2_RRAe,encoder__Condition2_RRAn,encoder__Condition2_RRNn,encoder__BldgType_1Fam,encoder__BldgType_2fmCon,encoder__BldgType_Duplex,encoder__BldgType_Twnhs,encoder__BldgType_TwnhsE,encoder__HouseStyle_1.5Fin,encoder__HouseStyle_1.5Unf,encoder__HouseStyle_1Story,encoder__HouseStyle_2.5Fin,encoder__HouseStyle_2.5Unf,encoder__HouseStyle_2Story,encoder__HouseStyle_SFoyer,encoder__HouseStyle_SLvl,encoder__RoofStyle_Flat,encoder__RoofStyle_Gable,encoder__RoofStyle_Gambrel,encoder__RoofStyle_Hip,encoder__RoofStyle_Mansard,encoder__RoofStyle_Shed,encoder__RoofMatl_ClyTile,encoder__RoofMatl_CompShg,encoder__RoofMatl_Membran,encoder__RoofMatl_Metal,encoder__RoofMatl_Roll,encoder__RoofMatl_Tar&Grv,encoder__RoofMatl_WdShake,encoder__RoofMatl_WdShngl,encoder__Exterior1st_AsbShng,encoder__Exterior1st_AsphShn,encoder__Exterior1st_BrkComm,encoder__Exterior1st_BrkFace,encoder__Exterior1st_CBlock,encoder__Exterior1st_CemntBd,encoder__Exterior1st_HdBoard,encoder__Exterior1st_ImStucc,encoder__Exterior1st_MetalSd,encoder__Exterior1st_Plywood,encoder__Exterior1st_Stone,encoder__Exterior1st_Stucco,encoder__Exterior1st_VinylSd,encoder__Exterior1st_Wd Sdng,encoder__Exterior1st_WdShing,encoder__Exterior2nd_AsbShng,encoder__Exterior2nd_AsphShn,encoder__Exterior2nd_Brk Cmn,encoder__Exterior2nd_BrkFace,encoder__Exterior2nd_CBlock,encoder__Exterior2nd_CmentBd,encoder__Exterior2nd_HdBoard,encoder__Exterior2nd_ImStucc,encoder__Exterior2nd_MetalSd,encoder__Exterior2nd_Other,encoder__Exterior2nd_Plywood,encoder__Exterior2nd_Stone,encoder__Exterior2nd_Stucco,encoder__Exterior2nd_VinylSd,encoder__Exterior2nd_Wd Sdng,encoder__Exterior2nd_Wd Shng,encoder__MasVnrType_BrkCmn,encoder__MasVnrType_BrkFace,encoder__MasVnrType_Stone,encoder__MasVnrType_nan,encoder__ExterQual_Ex,encoder__ExterQual_Fa,encoder__ExterQual_Gd,encoder__ExterQual_TA,encoder__ExterCond_Ex,encoder__ExterCond_Fa,encoder__ExterCond_Gd,encoder__ExterCond_Po,encoder__ExterCond_TA,encoder__Foundation_BrkTil,encoder__Foundation_CBlock,encoder__Foundation_PConc,encoder__Foundation_Slab,encoder__Foundation_Stone,encoder__Foundation_Wood,encoder__BsmtQual_Ex,encoder__BsmtQual_Fa,encoder__BsmtQual_Gd,encoder__BsmtQual_TA,encoder__BsmtQual_nan,encoder__BsmtCond_Fa,encoder__BsmtCond_Gd,encoder__BsmtCond_Po,encoder__BsmtCond_TA,encoder__BsmtCond_nan,encoder__BsmtExposure_Av,encoder__BsmtExposure_Gd,encoder__BsmtExposure_Mn,encoder__BsmtExposure_No,encoder__BsmtExposure_nan,encoder__BsmtFinType1_ALQ,encoder__BsmtFinType1_BLQ,encoder__BsmtFinType1_GLQ,encoder__BsmtFinType1_LwQ,encoder__BsmtFinType1_Rec,encoder__BsmtFinType1_Unf,encoder__BsmtFinType1_nan,encoder__BsmtFinType2_ALQ,encoder__BsmtFinType2_BLQ,encoder__BsmtFinType2_GLQ,encoder__BsmtFinType2_LwQ,encoder__BsmtFinType2_Rec,encoder__BsmtFinType2_Unf,encoder__BsmtFinType2_nan,encoder__Heating_Floor,encoder__Heating_GasA,encoder__Heating_GasW,encoder__Heating_Grav,encoder__Heating_OthW,encoder__Heating_Wall,encoder__HeatingQC_Ex,encoder__HeatingQC_Fa,encoder__HeatingQC_Gd,encoder__HeatingQC_Po,encoder__HeatingQC_TA,encoder__CentralAir_N,encoder__CentralAir_Y,encoder__Electrical_FuseA,encoder__Electrical_FuseF,encoder__Electrical_FuseP,encoder__Electrical_Mix,encoder__Electrical_SBrkr,encoder__Electrical_nan,encoder__KitchenQual_Ex,encoder__KitchenQual_Fa,encoder__KitchenQual_Gd,encoder__KitchenQual_TA,encoder__Functional_Maj1,encoder__Functional_Maj2,encoder__Functional_Min1,encoder__Functional_Min2,encoder__Functional_Mod,encoder__Functional_Sev,encoder__Functional_Typ,encoder__FireplaceQu_Ex,encoder__FireplaceQu_Fa,encoder__FireplaceQu_Gd,encoder__FireplaceQu_Po,encoder__FireplaceQu_TA,encoder__FireplaceQu_nan,encoder__GarageType_2Types,encoder__GarageType_Attchd,encoder__GarageType_Basment,encoder__GarageType_BuiltIn,encoder__GarageType_CarPort,encoder__GarageType_Detchd,encoder__GarageType_nan,encoder__GarageFinish_Fin,encoder__GarageFinish_RFn,encoder__GarageFinish_Unf,encoder__GarageFinish_nan,encoder__GarageQual_Ex,encoder__GarageQual_Fa,encoder__GarageQual_Gd,encoder__GarageQual_Po,encoder__GarageQual_TA,encoder__GarageQual_nan,encoder__GarageCond_Ex,encoder__GarageCond_Fa,encoder__GarageCond_Gd,encoder__GarageCond_Po,encoder__GarageCond_TA,encoder__GarageCond_nan,encoder__PavedDrive_N,encoder__PavedDrive_P,encoder__PavedDrive_Y,encoder__PoolQC_Ex,encoder__PoolQC_Fa,encoder__PoolQC_Gd,encoder__PoolQC_nan,encoder__Fence_GdPrv,encoder__Fence_GdWo,encoder__Fence_MnPrv,encoder__Fence_MnWw,encoder__Fence_nan,encoder__MiscFeature_Gar2,encoder__MiscFeature_Othr,encoder__MiscFeature_Shed,encoder__MiscFeature_TenC,encoder__MiscFeature_nan,encoder__SaleType_COD,encoder__SaleType_CWD,encoder__SaleType_Con,encoder__SaleType_ConLD,encoder__SaleType_ConLI,encoder__SaleType_ConLw,encoder__SaleType_New,encoder__SaleType_Oth,encoder__SaleType_WD,encoder__SaleCondition_Abnorml,encoder__SaleCondition_AdjLand,encoder__SaleCondition_Alloca,encoder__SaleCondition_Family,encoder__SaleCondition_Normal,encoder__SaleCondition_Partial,remainder__MSSubClass,remainder__LotFrontage,remainder__LotArea,remainder__OverallQual,remainder__OverallCond,remainder__YearBuilt,remainder__YearRemodAdd,remainder__MasVnrArea,remainder__BsmtFinSF1,remainder__BsmtFinSF2,remainder__BsmtUnfSF,remainder__TotalBsmtSF,remainder__1stFlrSF,remainder__2ndFlrSF,remainder__LowQualFinSF,remainder__GrLivArea,remainder__BsmtFullBath,remainder__BsmtHalfBath,remainder__FullBath,remainder__HalfBath,remainder__BedroomAbvGr,remainder__KitchenAbvGr,remainder__TotRmsAbvGrd,remainder__Fireplaces,remainder__GarageYrBlt,remainder__GarageCars,remainder__GarageArea,remainder__WoodDeckSF,remainder__OpenPorchSF,remainder__EnclosedPorch,remainder__3SsnPorch,remainder__ScreenPorch,remainder__PoolArea,remainder__MiscVal,remainder__MoSold,remainder__YrSold,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,60.0,65.0,8450.0,7.0,5.0,2003.0,2003.0,196.0,706.0,0.0,150.0,856.0,856.0,854.0,0.0,1710.0,1.0,0.0,2.0,1.0,3.0,1.0,8.0,0.0,2003.0,2.0,548.0,0.0,61.0,0.0,0.0,0.0,0.0,0.0,2.0,2008.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,60.0,65.0,8450.0,7.0,5.0,2003.0,2003.0,196.0,706.0,0.0,150.0,856.0,856.0,854.0,0.0,1710.0,1.0,0.0,2.0,1.0,3.0,1.0,8.0,0.0,2003.0,2.0,548.0,0.0,61.0,0.0,0.0,0.0,0.0,0.0,2.0,2008.0,208500
2,20.0,80.0,9600.0,6.0,8.0,1976.0,1976.0,0.0,978.0,0.0,284.0,1262.0,1262.0,0.0,0.0,1262.0,0.0,1.0,2.0,0.0,3.0,1.0,6.0,1.0,1976.0,2.0,460.0,298.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,2007.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,20.0,80.0,9600.0,6.0,8.0,1976.0,1976.0,0.0,978.0,0.0,284.0,1262.0,1262.0,0.0,0.0,1262.0,0.0,1.0,2.0,0.0,3.0,1.0,6.0,1.0,1976.0,2.0,460.0,298.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,2007.0,181500
3,60.0,68.0,11250.0,7.0,5.0,2001.0,2002.0,162.0,486.0,0.0,434.0,920.0,920.0,866.0,0.0,1786.0,1.0,0.0,2.0,1.0,3.0,1.0,6.0,1.0,2001.0,2.0,608.0,0.0,42.0,0.0,0.0,0.0,0.0,0.0,9.0,2008.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,60.0,68.0,11250.0,7.0,5.0,2001.0,2002.0,162.0,486.0,0.0,434.0,920.0,920.0,866.0,0.0,1786.0,1.0,0.0,2.0,1.0,3.0,1.0,6.0,1.0,2001.0,2.0,608.0,0.0,42.0,0.0,0.0,0.0,0.0,0.0,9.0,2008.0,223500
4,70.0,60.0,9550.0,7.0,5.0,1915.0,1970.0,0.0,216.0,0.0,540.0,756.0,961.0,756.0,0.0,1717.0,1.0,0.0,1.0,0.0,3.0,1.0,7.0,1.0,1998.0,3.0,642.0,0.0,35.0,272.0,0.0,0.0,0.0,0.0,2.0,2006.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,70.0,60.0,9550.0,7.0,5.0,1915.0,1970.0,0.0,216.0,0.0,540.0,756.0,961.0,756.0,0.0,1717.0,1.0,0.0,1.0,0.0,3.0,1.0,7.0,1.0,1998.0,3.0,642.0,0.0,35.0,272.0,0.0,0.0,0.0,0.0,2.0,2006.0,140000
5,60.0,84.0,14260.0,8.0,5.0,2000.0,2000.0,350.0,655.0,0.0,490.0,1145.0,1145.0,1053.0,0.0,2198.0,1.0,0.0,2.0,1.0,4.0,1.0,9.0,1.0,2000.0,3.0,836.0,192.0,84.0,0.0,0.0,0.0,0.0,0.0,12.0,2008.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,60.0,84.0,14260.0,8.0,5.0,2000.0,2000.0,350.0,655.0,0.0,490.0,1145.0,1145.0,1053.0,0.0,2198.0,1.0,0.0,2.0,1.0,4.0,1.0,9.0,1.0,2000.0,3.0,836.0,192.0,84.0,0.0,0.0,0.0,0.0,0.0,12.0,2008.0,250000

In [193]:
#house_df.head()

In [346]:
features = numeric_cols

In [478]:
x = house_new_df.iloc[:,:-1]

In [479]:
y = house_new_df.iloc[:,-1]

In [480]:
x.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,encoder__MSZoning_C (all),encoder__MSZoning_FV,encoder__MSZoning_RH,encoder__MSZoning_RL,encoder__MSZoning_RM,encoder__Street_Grvl,encoder__Street_Pave,encoder__Alley_Grvl,encoder__Alley_Pave,encoder__Alley_nan,encoder__LotShape_IR1,encoder__LotShape_IR2,encoder__LotShape_IR3,encoder__LotShape_Reg,encoder__LandContour_Bnk,encoder__LandContour_HLS,encoder__LandContour_Low,encoder__LandContour_Lvl,encoder__Utilities_AllPub,encoder__Utilities_NoSeWa,encoder__LotConfig_Corner,encoder__LotConfig_CulDSac,encoder__LotConfig_FR2,encoder__LotConfig_FR3,encoder__LotConfig_Inside,encoder__LandSlope_Gtl,encoder__LandSlope_Mod,encoder__LandSlope_Sev,encoder__Neighborhood_Blmngtn,encoder__Neighborhood_Blueste,encoder__Neighborhood_BrDale,encoder__Neighborhood_BrkSide,encoder__Neighborhood_ClearCr,encoder__Neighborhood_CollgCr,encoder__Neighborhood_Crawfor,encoder__Neighborhood_Edwards,encoder__Neighborhood_Gilbert,encoder__Neighborhood_IDOTRR,encoder__Neighborhood_MeadowV,encoder__Neighborhood_Mitchel,encoder__Neighborhood_NAmes,encoder__Neighborhood_NPkVill,encoder__Neighborhood_NWAmes,encoder__Neighborhood_NoRidge,encoder__Neighborhood_NridgHt,encoder__Neighborhood_OldTown,encoder__Neighborhood_SWISU,encoder__Neighborhood_Sawyer,encoder__Neighborhood_SawyerW,encoder__Neighborhood_Somerst,encoder__Neighborhood_StoneBr,encoder__Neighborhood_Timber,encoder__Neighborhood_Veenker,encoder__Condition1_Artery,encoder__Condition1_Feedr,encoder__Condition1_Norm,encoder__Condition1_PosA,encoder__Condition1_PosN,encoder__Condition1_RRAe,encoder__Condition1_RRAn,encoder__Condition1_RRNe,encoder__Condition1_RRNn,encoder__Condition2_Artery,encoder__Condition2_Feedr,encoder__Condition2_Norm,encoder__Condition2_PosA,encoder__Condition2_PosN,encoder__Condition2_RRAe,encoder__Condition2_RRAn,encoder__Condition2_RRNn,encoder__BldgType_1Fam,encoder__BldgType_2fmCon,encoder__BldgType_Duplex,encoder__BldgType_Twnhs,encoder__BldgType_TwnhsE,encoder__HouseStyle_1.5Fin,encoder__HouseStyle_1.5Unf,encoder__HouseStyle_1Story,encoder__HouseStyle_2.5Fin,encoder__HouseStyle_2.5Unf,encoder__HouseStyle_2Story,encoder__HouseStyle_SFoyer,encoder__HouseStyle_SLvl,encoder__RoofStyle_Flat,encoder__RoofStyle_Gable,encoder__RoofStyle_Gambrel,encoder__RoofStyle_Hip,encoder__RoofStyle_Mansard,encoder__RoofStyle_Shed,encoder__RoofMatl_ClyTile,encoder__RoofMatl_CompShg,encoder__RoofMatl_Membran,encoder__RoofMatl_Metal,encoder__RoofMatl_Roll,encoder__RoofMatl_Tar&Grv,encoder__RoofMatl_WdShake,encoder__RoofMatl_WdShngl,encoder__Exterior1st_AsbShng,encoder__Exterior1st_AsphShn,encoder__Exterior1st_BrkComm,encoder__Exterior1st_BrkFace,encoder__Exterior1st_CBlock,encoder__Exterior1st_CemntBd,encoder__Exterior1st_HdBoard,encoder__Exterior1st_ImStucc,encoder__Exterior1st_MetalSd,encoder__Exterior1st_Plywood,encoder__Exterior1st_Stone,encoder__Exterior1st_Stucco,encoder__Exterior1st_VinylSd,encoder__Exterior1st_Wd Sdng,encoder__Exterior1st_WdShing,encoder__Exterior2nd_AsbShng,encoder__Exterior2nd_AsphShn,encoder__Exterior2nd_Brk Cmn,encoder__Exterior2nd_BrkFace,encoder__Exterior2nd_CBlock,encoder__Exterior2nd_CmentBd,encoder__Exterior2nd_HdBoard,encoder__Exterior2nd_ImStucc,encoder__Exterior2nd_MetalSd,encoder__Exterior2nd_Other,encoder__Exterior2nd_Plywood,encoder__Exterior2nd_Stone,encoder__Exterior2nd_Stucco,encoder__Exterior2nd_VinylSd,encoder__Exterior2nd_Wd Sdng,encoder__Exterior2nd_Wd Shng,encoder__MasVnrType_BrkCmn,encoder__MasVnrType_BrkFace,encoder__MasVnrType_Stone,encoder__MasVnrType_nan,encoder__ExterQual_Ex,encoder__ExterQual_Fa,encoder__ExterQual_Gd,encoder__ExterQual_TA,encoder__ExterCond_Ex,encoder__ExterCond_Fa,encoder__ExterCond_Gd,encoder__ExterCond_Po,encoder__ExterCond_TA,encoder__Foundation_BrkTil,encoder__Foundation_CBlock,encoder__Foundation_PConc,encoder__Foundation_Slab,encoder__Foundation_Stone,encoder__Foundation_Wood,encoder__BsmtQual_Ex,encoder__BsmtQual_Fa,encoder__BsmtQual_Gd,encoder__BsmtQual_TA,encoder__BsmtQual_nan,encoder__BsmtCond_Fa,encoder__BsmtCond_Gd,encoder__BsmtCond_Po,encoder__BsmtCond_TA,encoder__BsmtCond_nan,encoder__BsmtExposure_Av,encoder__BsmtExposure_Gd,encoder__BsmtExposure_Mn,encoder__BsmtExposure_No,encoder__BsmtExposure_nan,encoder__BsmtFinType1_ALQ,encoder__BsmtFinType1_BLQ,encoder__BsmtFinType1_GLQ,encoder__BsmtFinType1_LwQ,encoder__BsmtFinType1_Rec,encoder__BsmtFinType1_Unf,encoder__BsmtFinType1_nan,encoder__BsmtFinType2_ALQ,encoder__BsmtFinType2_BLQ,encoder__BsmtFinType2_GLQ,encoder__BsmtFinType2_LwQ,encoder__BsmtFinType2_Rec,encoder__BsmtFinType2_Unf,encoder__BsmtFinType2_nan,encoder__Heating_Floor,encoder__Heating_GasA,encoder__Heating_GasW,encoder__Heating_Grav,encoder__Heating_OthW,encoder__Heating_Wall,encoder__HeatingQC_Ex,encoder__HeatingQC_Fa,encoder__HeatingQC_Gd,encoder__HeatingQC_Po,encoder__HeatingQC_TA,encoder__CentralAir_N,encoder__CentralAir_Y,encoder__Electrical_FuseA,encoder__Electrical_FuseF,encoder__Electrical_FuseP,encoder__Electrical_Mix,encoder__Electrical_SBrkr,encoder__Electrical_nan,encoder__KitchenQual_Ex,encoder__KitchenQual_Fa,encoder__KitchenQual_Gd,encoder__KitchenQual_TA,encoder__Functional_Maj1,encoder__Functional_Maj2,encoder__Functional_Min1,encoder__Functional_Min2,encoder__Functional_Mod,encoder__Functional_Sev,encoder__Functional_Typ,encoder__FireplaceQu_Ex,encoder__FireplaceQu_Fa,encoder__FireplaceQu_Gd,encoder__FireplaceQu_Po,encoder__FireplaceQu_TA,encoder__FireplaceQu_nan,encoder__GarageType_2Types,encoder__GarageType_Attchd,encoder__GarageType_Basment,encoder__GarageType_BuiltIn,encoder__GarageType_CarPort,encoder__GarageType_Detchd,encoder__GarageType_nan,encoder__GarageFinish_Fin,encoder__GarageFinish_RFn,encoder__GarageFinish_Unf,encoder__GarageFinish_nan,encoder__GarageQual_Ex,encoder__GarageQual_Fa,encoder__GarageQual_Gd,encoder__GarageQual_Po,encoder__GarageQual_TA,encoder__GarageQual_nan,encoder__GarageCond_Ex,encoder__GarageCond_Fa,encoder__GarageCond_Gd,encoder__GarageCond_Po,encoder__GarageCond_TA,encoder__GarageCond_nan,encoder__PavedDrive_N,encoder__PavedDrive_P,encoder__PavedDrive_Y,encoder__PoolQC_Ex,encoder__PoolQC_Fa,encoder__PoolQC_Gd,encoder__PoolQC_nan,encoder__Fence_GdPrv,encoder__Fence_GdWo,encoder__Fence_MnPrv,encoder__Fence_MnWw,encoder__Fence_nan,encoder__MiscFeature_Gar2,encoder__MiscFeature_Othr,encoder__MiscFeature_Shed,encoder__MiscFeature_TenC,encoder__MiscFeature_nan,encoder__SaleType_COD,encoder__SaleType_CWD,encoder__SaleType_Con,encoder__SaleType_ConLD,encoder__SaleType_ConLI,encoder__SaleType_ConLw,encoder__SaleType_New,encoder__SaleType_Oth,encoder__SaleType_WD,encoder__SaleCondition_Abnorml,encoder__SaleCondition_AdjLand,encoder__SaleCondition_Alloca,encoder__SaleCondition_Family,encoder__SaleCondition_Normal,encoder__SaleCondition_Partial,remainder__MSSubClass,remainder__LotFrontage,remainder__LotArea,remainder__OverallQual,remainder__OverallCond,remainder__YearBuilt,remainder__YearRemodAdd,remainder__MasVnrArea,remainder__BsmtFinSF1,remainder__BsmtFinSF2,remainder__BsmtUnfSF,remainder__TotalBsmtSF,remainder__1stFlrSF,remainder__2ndFlrSF,remainder__LowQualFinSF,remainder__GrLivArea,remainder__BsmtFullBath,remainder__BsmtHalfBath,remainder__FullBath,remainder__HalfBath,remainder__BedroomAbvGr,remainder__KitchenAbvGr,remainder__TotRmsAbvGrd,remainder__Fireplaces,remainder__GarageYrBlt,remainder__GarageCars,remainder__GarageArea,remainder__WoodDeckSF,remainder__OpenPorchSF,remainder__EnclosedPorch,remainder__3SsnPorch,remainder__ScreenPorch,remainder__PoolArea,remainder__MiscVal,remainder__MoSold,remainder__YrSold
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,60.0,65.0,8450.0,7.0,5.0,2003.0,2003.0,196.0,706.0,0.0,150.0,856.0,856.0,854.0,0.0,1710.0,1.0,0.0,2.0,1.0,3.0,1.0,8.0,0.0,2003.0,2.0,548.0,0.0,61.0,0.0,0.0,0.0,0.0,0.0,2.0,2008.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,60.0,65.0,8450.0,7.0,5.0,2003.0,2003.0,196.0,706.0,0.0,150.0,856.0,856.0,854.0,0.0,1710.0,1.0,0.0,2.0,1.0,3.0,1.0,8.0,0.0,2003.0,2.0,548.0,0.0,61.0,0.0,0.0,0.0,0.0,0.0,2.0,2008.0
2,20.0,80.0,9600.0,6.0,8.0,1976.0,1976.0,0.0,978.0,0.0,284.0,1262.0,1262.0,0.0,0.0,1262.0,0.0,1.0,2.0,0.0,3.0,1.0,6.0,1.0,1976.0,2.0,460.0,298.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,2007.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,20.0,80.0,9600.0,6.0,8.0,1976.0,1976.0,0.0,978.0,0.0,284.0,1262.0,1262.0,0.0,0.0,1262.0,0.0,1.0,2.0,0.0,3.0,1.0,6.0,1.0,1976.0,2.0,460.0,298.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,2007.0
3,60.0,68.0,11250.0,7.0,5.0,2001.0,2002.0,162.0,486.0,0.0,434.0,920.0,920.0,866.0,0.0,1786.0,1.0,0.0,2.0,1.0,3.0,1.0,6.0,1.0,2001.0,2.0,608.0,0.0,42.0,0.0,0.0,0.0,0.0,0.0,9.0,2008.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,60.0,68.0,11250.0,7.0,5.0,2001.0,2002.0,162.0,486.0,0.0,434.0,920.0,920.0,866.0,0.0,1786.0,1.0,0.0,2.0,1.0,3.0,1.0,6.0,1.0,2001.0,2.0,608.0,0.0,42.0,0.0,0.0,0.0,0.0,0.0,9.0,2008.0
4,70.0,60.0,9550.0,7.0,5.0,1915.0,1970.0,0.0,216.0,0.0,540.0,756.0,961.0,756.0,0.0,1717.0,1.0,0.0,1.0,0.0,3.0,1.0,7.0,1.0,1998.0,3.0,642.0,0.0,35.0,272.0,0.0,0.0,0.0,0.0,2.0,2006.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,70.0,60.0,9550.0,7.0,5.0,1915.0,1970.0,0.0,216.0,0.0,540.0,756.0,961.0,756.0,0.0,1717.0,1.0,0.0,1.0,0.0,3.0,1.0,7.0,1.0,1998.0,3.0,642.0,0.0,35.0,272.0,0.0,0.0,0.0,0.0,2.0,2006.0
5,60.0,84.0,14260.0,8.0,5.0,2000.0,2000.0,350.0,655.0,0.0,490.0,1145.0,1145.0,1053.0,0.0,2198.0,1.0,0.0,2.0,1.0,4.0,1.0,9.0,1.0,2000.0,3.0,836.0,192.0,84.0,0.0,0.0,0.0,0.0,0.0,12.0,2008.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,60.0,84.0,14260.0,8.0,5.0,2000.0,2000.0,350.0,655.0,0.0,490.0,1145.0,1145.0,1053.0,0.0,2198.0,1.0,0.0,2.0,1.0,4.0,1.0,9.0,1.0,2000.0,3.0,836.0,192.0,84.0,0.0,0.0,0.0,0.0,0.0,12.0,2008.0

In [481]:
x.shape

(1460, 339)

In [482]:
y.head()

Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

In [483]:
from sklearn.model_selection import train_test_split
x_train, x_valid, y_train, y_valid = train_test_split(x,y,train_size = 0.8, test_size = 0.2, random_state = 0)

In [484]:
x_train.shape

(1168, 339)

In [485]:
x_valid

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,encoder__MSZoning_C (all),encoder__MSZoning_FV,encoder__MSZoning_RH,encoder__MSZoning_RL,encoder__MSZoning_RM,encoder__Street_Grvl,encoder__Street_Pave,encoder__Alley_Grvl,encoder__Alley_Pave,encoder__Alley_nan,encoder__LotShape_IR1,encoder__LotShape_IR2,encoder__LotShape_IR3,encoder__LotShape_Reg,encoder__LandContour_Bnk,encoder__LandContour_HLS,encoder__LandContour_Low,encoder__LandContour_Lvl,encoder__Utilities_AllPub,encoder__Utilities_NoSeWa,encoder__LotConfig_Corner,encoder__LotConfig_CulDSac,encoder__LotConfig_FR2,encoder__LotConfig_FR3,encoder__LotConfig_Inside,encoder__LandSlope_Gtl,encoder__LandSlope_Mod,encoder__LandSlope_Sev,encoder__Neighborhood_Blmngtn,encoder__Neighborhood_Blueste,encoder__Neighborhood_BrDale,encoder__Neighborhood_BrkSide,encoder__Neighborhood_ClearCr,encoder__Neighborhood_CollgCr,encoder__Neighborhood_Crawfor,encoder__Neighborhood_Edwards,encoder__Neighborhood_Gilbert,encoder__Neighborhood_IDOTRR,encoder__Neighborhood_MeadowV,encoder__Neighborhood_Mitchel,encoder__Neighborhood_NAmes,encoder__Neighborhood_NPkVill,encoder__Neighborhood_NWAmes,encoder__Neighborhood_NoRidge,encoder__Neighborhood_NridgHt,encoder__Neighborhood_OldTown,encoder__Neighborhood_SWISU,encoder__Neighborhood_Sawyer,encoder__Neighborhood_SawyerW,encoder__Neighborhood_Somerst,encoder__Neighborhood_StoneBr,encoder__Neighborhood_Timber,encoder__Neighborhood_Veenker,encoder__Condition1_Artery,encoder__Condition1_Feedr,encoder__Condition1_Norm,encoder__Condition1_PosA,encoder__Condition1_PosN,encoder__Condition1_RRAe,encoder__Condition1_RRAn,encoder__Condition1_RRNe,encoder__Condition1_RRNn,encoder__Condition2_Artery,encoder__Condition2_Feedr,encoder__Condition2_Norm,encoder__Condition2_PosA,encoder__Condition2_PosN,encoder__Condition2_RRAe,encoder__Condition2_RRAn,encoder__Condition2_RRNn,encoder__BldgType_1Fam,encoder__BldgType_2fmCon,encoder__BldgType_Duplex,encoder__BldgType_Twnhs,encoder__BldgType_TwnhsE,encoder__HouseStyle_1.5Fin,encoder__HouseStyle_1.5Unf,encoder__HouseStyle_1Story,encoder__HouseStyle_2.5Fin,encoder__HouseStyle_2.5Unf,encoder__HouseStyle_2Story,encoder__HouseStyle_SFoyer,encoder__HouseStyle_SLvl,encoder__RoofStyle_Flat,encoder__RoofStyle_Gable,encoder__RoofStyle_Gambrel,encoder__RoofStyle_Hip,encoder__RoofStyle_Mansard,encoder__RoofStyle_Shed,encoder__RoofMatl_ClyTile,encoder__RoofMatl_CompShg,encoder__RoofMatl_Membran,encoder__RoofMatl_Metal,encoder__RoofMatl_Roll,encoder__RoofMatl_Tar&Grv,encoder__RoofMatl_WdShake,encoder__RoofMatl_WdShngl,encoder__Exterior1st_AsbShng,encoder__Exterior1st_AsphShn,encoder__Exterior1st_BrkComm,encoder__Exterior1st_BrkFace,encoder__Exterior1st_CBlock,encoder__Exterior1st_CemntBd,encoder__Exterior1st_HdBoard,encoder__Exterior1st_ImStucc,encoder__Exterior1st_MetalSd,encoder__Exterior1st_Plywood,encoder__Exterior1st_Stone,encoder__Exterior1st_Stucco,encoder__Exterior1st_VinylSd,encoder__Exterior1st_Wd Sdng,encoder__Exterior1st_WdShing,encoder__Exterior2nd_AsbShng,encoder__Exterior2nd_AsphShn,encoder__Exterior2nd_Brk Cmn,encoder__Exterior2nd_BrkFace,encoder__Exterior2nd_CBlock,encoder__Exterior2nd_CmentBd,encoder__Exterior2nd_HdBoard,encoder__Exterior2nd_ImStucc,encoder__Exterior2nd_MetalSd,encoder__Exterior2nd_Other,encoder__Exterior2nd_Plywood,encoder__Exterior2nd_Stone,encoder__Exterior2nd_Stucco,encoder__Exterior2nd_VinylSd,encoder__Exterior2nd_Wd Sdng,encoder__Exterior2nd_Wd Shng,encoder__MasVnrType_BrkCmn,encoder__MasVnrType_BrkFace,encoder__MasVnrType_Stone,encoder__MasVnrType_nan,encoder__ExterQual_Ex,encoder__ExterQual_Fa,encoder__ExterQual_Gd,encoder__ExterQual_TA,encoder__ExterCond_Ex,encoder__ExterCond_Fa,encoder__ExterCond_Gd,encoder__ExterCond_Po,encoder__ExterCond_TA,encoder__Foundation_BrkTil,encoder__Foundation_CBlock,encoder__Foundation_PConc,encoder__Foundation_Slab,encoder__Foundation_Stone,encoder__Foundation_Wood,encoder__BsmtQual_Ex,encoder__BsmtQual_Fa,encoder__BsmtQual_Gd,encoder__BsmtQual_TA,encoder__BsmtQual_nan,encoder__BsmtCond_Fa,encoder__BsmtCond_Gd,encoder__BsmtCond_Po,encoder__BsmtCond_TA,encoder__BsmtCond_nan,encoder__BsmtExposure_Av,encoder__BsmtExposure_Gd,encoder__BsmtExposure_Mn,encoder__BsmtExposure_No,encoder__BsmtExposure_nan,encoder__BsmtFinType1_ALQ,encoder__BsmtFinType1_BLQ,encoder__BsmtFinType1_GLQ,encoder__BsmtFinType1_LwQ,encoder__BsmtFinType1_Rec,encoder__BsmtFinType1_Unf,encoder__BsmtFinType1_nan,encoder__BsmtFinType2_ALQ,encoder__BsmtFinType2_BLQ,encoder__BsmtFinType2_GLQ,encoder__BsmtFinType2_LwQ,encoder__BsmtFinType2_Rec,encoder__BsmtFinType2_Unf,encoder__BsmtFinType2_nan,encoder__Heating_Floor,encoder__Heating_GasA,encoder__Heating_GasW,encoder__Heating_Grav,encoder__Heating_OthW,encoder__Heating_Wall,encoder__HeatingQC_Ex,encoder__HeatingQC_Fa,encoder__HeatingQC_Gd,encoder__HeatingQC_Po,encoder__HeatingQC_TA,encoder__CentralAir_N,encoder__CentralAir_Y,encoder__Electrical_FuseA,encoder__Electrical_FuseF,encoder__Electrical_FuseP,encoder__Electrical_Mix,encoder__Electrical_SBrkr,encoder__Electrical_nan,encoder__KitchenQual_Ex,encoder__KitchenQual_Fa,encoder__KitchenQual_Gd,encoder__KitchenQual_TA,encoder__Functional_Maj1,encoder__Functional_Maj2,encoder__Functional_Min1,encoder__Functional_Min2,encoder__Functional_Mod,encoder__Functional_Sev,encoder__Functional_Typ,encoder__FireplaceQu_Ex,encoder__FireplaceQu_Fa,encoder__FireplaceQu_Gd,encoder__FireplaceQu_Po,encoder__FireplaceQu_TA,encoder__FireplaceQu_nan,encoder__GarageType_2Types,encoder__GarageType_Attchd,encoder__GarageType_Basment,encoder__GarageType_BuiltIn,encoder__GarageType_CarPort,encoder__GarageType_Detchd,encoder__GarageType_nan,encoder__GarageFinish_Fin,encoder__GarageFinish_RFn,encoder__GarageFinish_Unf,encoder__GarageFinish_nan,encoder__GarageQual_Ex,encoder__GarageQual_Fa,encoder__GarageQual_Gd,encoder__GarageQual_Po,encoder__GarageQual_TA,encoder__GarageQual_nan,encoder__GarageCond_Ex,encoder__GarageCond_Fa,encoder__GarageCond_Gd,encoder__GarageCond_Po,encoder__GarageCond_TA,encoder__GarageCond_nan,encoder__PavedDrive_N,encoder__PavedDrive_P,encoder__PavedDrive_Y,encoder__PoolQC_Ex,encoder__PoolQC_Fa,encoder__PoolQC_Gd,encoder__PoolQC_nan,encoder__Fence_GdPrv,encoder__Fence_GdWo,encoder__Fence_MnPrv,encoder__Fence_MnWw,encoder__Fence_nan,encoder__MiscFeature_Gar2,encoder__MiscFeature_Othr,encoder__MiscFeature_Shed,encoder__MiscFeature_TenC,encoder__MiscFeature_nan,encoder__SaleType_COD,encoder__SaleType_CWD,encoder__SaleType_Con,encoder__SaleType_ConLD,encoder__SaleType_ConLI,encoder__SaleType_ConLw,encoder__SaleType_New,encoder__SaleType_Oth,encoder__SaleType_WD,encoder__SaleCondition_Abnorml,encoder__SaleCondition_AdjLand,encoder__SaleCondition_Alloca,encoder__SaleCondition_Family,encoder__SaleCondition_Normal,encoder__SaleCondition_Partial,remainder__MSSubClass,remainder__LotFrontage,remainder__LotArea,remainder__OverallQual,remainder__OverallCond,remainder__YearBuilt,remainder__YearRemodAdd,remainder__MasVnrArea,remainder__BsmtFinSF1,remainder__BsmtFinSF2,remainder__BsmtUnfSF,remainder__TotalBsmtSF,remainder__1stFlrSF,remainder__2ndFlrSF,remainder__LowQualFinSF,remainder__GrLivArea,remainder__BsmtFullBath,remainder__BsmtHalfBath,remainder__FullBath,remainder__HalfBath,remainder__BedroomAbvGr,remainder__KitchenAbvGr,remainder__TotRmsAbvGrd,remainder__Fireplaces,remainder__GarageYrBlt,remainder__GarageCars,remainder__GarageArea,remainder__WoodDeckSF,remainder__OpenPorchSF,remainder__EnclosedPorch,remainder__3SsnPorch,remainder__ScreenPorch,remainder__PoolArea,remainder__MiscVal,remainder__MoSold,remainder__YrSold
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
530,20.0,70.049958,32668.0,6.0,3.0,1957.0,1975.0,103.685262,1219.0,0.0,816.0,2035.0,2515.0,0.0,0.0,2515.0,1.0,0.0,3.0,0.0,4.0,2.0,9.0,2.0,1975.000000,2.0,484.0,0.0,0.0,200.0,0.0,0.0,0.0,0.0,3.0,2007.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,20.0,70.049958,32668.0,6.0,3.0,1957.0,1975.0,103.685262,1219.0,0.0,816.0,2035.0,2515.0,0.0,0.0,2515.0,1.0,0.0,3.0,0.0,4.0,2.0,9.0,2.0,1975.000000,2.0,484.0,0.0,0.0,200.0,0.0,0.0,0.0,0.0,3.0,2007.0
492,50.0,79.000000,9490.0,6.0,7.0,1941.0,1950.0,0.000000,403.0,165.0,238.0,806.0,958.0,620.0,0.0,1578.0,1.0,0.0,1.0,0.0,3.0,1.0,5.0,2.0,1941.000000,1.0,240.0,0.0,0.0,32.0,0.0,0.0,0.0,0.0,8.0,2006.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,50.0,79.000000,9490.0,6.0,7.0,1941.0,1950.0,0.000000,403.0,165.0,238.0,806.0,958.0,620.0,0.0,1578.0,1.0,0.0,1.0,0.0,3.0,1.0,5.0,2.0,1941.000000,1.0,240.0,0.0,0.0,32.0,0.0,0.0,0.0,0.0,8.0,2006.0
460,50.0,70.049958,7015.0,5.0,4.0,1950.0,1950.0,161.000000,185.0,0.0,524.0,709.0,979.0,224.0,0.0,1203.0,1.0,0.0,1.0,0.0,3.0,1.0,5.0,1.0,1950.000000,1.0,352.0,0.0,0.0,248.0,0.0,0.0,0.0,0.0,7.0,2009.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,50.0,70.049958,7015.0,5.0,4.0,1950.0,1950.0,161.000000,185.0,0.0,524.0,709.0,979.0,224.0,0.0,1203.0,1.0,0.0,1.0,0.0,3.0,1.0,5.0,1.0,1950.000000,1.0,352.0,0.0,0.0,248.0,0.0,0.0,0.0,0.0,7.0,2009.0
280,60.0,83.000000,10005.0,7.0,5.0,1977.0,1977.0,299.000000,392.0,0.0,768.0,1160.0,1156.0,866.0,0.0,2022.0,0.0,0.0,2.0,1.0,4.0,1.0,8.0,1.0,1977.000000,2.0,505.0,288.0,117.0,0.0,0.0,0.0,0.0,0.0,3.0,2008.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,60.0,83.000000,10005.0,7.0,5.0,1977.0,1977.0,299.000000,392.0,0.0,768.0,1160.0,1156.0,866.0,0.0,2022.0,0.0,0.0,2.0,1.0,4.0,1.0,8.0,1.0,1977.000000,2.0,505.0,288.0,117.0,0.0,0.0,0.0,0.0,0.0,3.0,2008.0
656,160.0,21.000000,1680.0,6.0,5.0,1971.0,1971.0,381.000000,0.0,0.0,525.0,525.0,525.0,567.0,0.0,1092.0,0.0,0.0,1.0,1.0,3.0,1.0,6.0,0.0,1971.000000,1.0,264.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,2010.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,160.0,21.000000,1680.0,6.0,5.0,1971.0,1971.0,381.000000,0.0,0.0,525.0,525.0,525.0,567.0,0.0,1092.0,0.0,0.0,1.0,1.0,3.0,1.0,6.0,0.0,1971.000000,1.0,264.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,2010.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,120.0,32.000000,10846.0,8.0,5.0,1993.0,1993.0,0.000000,1619.0,0.0,100.0,1719.0,1719.0,0.0,0.0,1719.0,2.0,0.0,1.0,1.0,1.0,1.0,6.0,2.0,1993.000000,2.0,473.0,122.0,30.0,0.0,0.0,0.0,0.0,0.0,5.0,2008.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,120.0,32.000000,10846.0,8.0,5.0,1993.0,1993.0,0.000000,1619.0,0.0,100.0,1719.0,1719.0,0.0,0.0,1719.0,2.0,0.0,1.0,1.0,1.0,1.0,6.0,2.0,1993.000000,2.0,473.0,122.0,30.0,0.0,0.0,0.0,0.0,0.0,5.0,2008.0
441,20.0,105.000000,15431.0,10.0,5.0,2008.0,2008.0,200.000000,1767.0,539.0,788.0,3094.0,2402.0,0.0,0.0,2402.0,1.0,0.0,2.0,0.0,2.0,1.0,10.0,2.0,2008.000000,3.0,672.0,0.0,72.0,0.0,0.0,170.0,0.0,0.0,4.0,2009.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,20.0,105.000000,15431.0,10.0,5.0,2008.0,2008.0,200.000000,1767.0,539.0,788.0,3094.0,2402.0,0.0,0.0,2402.0,1.0,0.0,2.0,0.0,2.0,1.0,10.0,2.0,2008.000000,3.0,672.0,0.0,72.0,0.0,0.0,170.0,0.0,0.0,4.0,2009.0

In [486]:
x_valid.shape

(292, 339)

In [487]:
from sklearn.tree import DecisionTreeRegressor
dt_model = DecisionTreeRegressor(random_state = 1)

In [488]:
dt_model.fit(x_train,y_train)

DecisionTreeRegressor(random_state=1)

In [489]:
dt_model.predict(x_valid)

array([237500., 113000., 120000., 221000.,  94500., 100000., 245000.,
       114500., 755000., 151000., 196000., 143000., 222500., 135500.,
       142000., 163000., 236000., 119900., 157000., 311500., 135000.,
       141000.,  55993., 178000., 179900., 318000., 172400.,  75500.,
       337500.,  89000., 124500., 185000., 122000., 281000., 423000.,
       198900., 326000., 125000., 219500., 381000., 237500., 159500.,
       159895., 318000., 315000., 161500., 120000., 143250., 220000.,
       108000., 426000., 149900., 169990.,  93000., 311872., 109008.,
       167500., 232600., 155000., 125000., 159500., 125000., 141000.,
       149900., 217000., 140000.,  89000., 205950., 154900., 165400.,
       178400., 119000.,  93500., 147000.,  66500., 147000., 135500.,
       100000., 290000., 181000., 140000., 133900., 109900., 140000.,
       169000., 210000., 102776., 202500., 162500., 141000., 207500.,
       171000., 184000., 205000., 178000., 148000., 204000., 274970.,
       109008., 133000., 248328., 294000., 137500., 124900.,  91300.,
       267000., 156000.,  96500., 177000.,  91500.,  52500., 155000.,
       146000., 132000., 154000., 148500., 380000., 138500., 177000.,
       252000., 200100., 171900., 140000., 221000., 227000., 250580.,
       380000., 187500., 179665., 159000., 246578., 176485., 190000.,
       130500., 109008., 248328., 115000., 202500., 105500., 183200.,
       109000., 140000., 274970., 152000., 235000., 201000., 213500.,
       147000., 264132., 246578., 188000., 326000., 314813., 176500.,
       209500., 266500., 108500., 215000.,  84500., 180000., 120500.,
       148000., 205950.,  93500., 232600., 127000., 128500., 315750.,
       210000., 189000., 130500., 148500., 169990., 142500., 143250.,
       118000., 109000., 250000., 104900., 152000., 350000., 215000.,
        91300., 297000., 143250., 230000., 100000., 195400., 178000.,
       143000., 140000., 179900., 201000., 109900., 125500., 140000.,
        86000., 123000., 154000., 155000., 132000., 245000., 147000.,
        84500., 127000., 158000., 148000., 437154., 230000.,  79000.,
       155000., 278000.,  93500.,  89000., 325000., 274970., 226000.,
       266500., 225000.,  86000., 226000., 127500., 139000., 115000.,
       171750., 215000., 350000., 186500., 144000., 159895.,  90000.,
       200100., 100000., 145000., 222500.,  97500., 135000., 127500.,
        79000., 143000., 119000., 274970., 188000., 231500., 164500.,
       197000., 213500., 215200., 127500., 189000., 194000., 252000.,
        85000., 342643., 244600., 239799.,  75500., 234000., 381000.,
       184750., 192000., 167500., 124000.,  79000., 426000., 402861.,
       402000.,  60000., 214000., 179900., 124000., 219210., 145000.,
       181000., 113000., 214900., 283463., 201800., 215000.,  94750.,
       122000., 326000., 159000., 145250., 176000., 121500., 119500.,
       275000., 466500., 113000.,  76500.,  73000.])

In [490]:
y_predis = dt_model.predict(x_valid)

In [207]:
#y_predis

In [491]:
pd.DataFrame({"y": y_valid, "y_predis": y_predis})

           y  y_predis
Id
530   200624  237500.0
492   133000  113000.0
460   110000  120000.0
280   192000  221000.0
656    88000   94500.0
...      ...       ...
327   324000  275000.0
441   555000  466500.0
1388  136000  113000.0
1324   82500   76500.0
62    101000   73000.0

[292 rows x 2 columns]

In [492]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
rf_model = RandomForestRegressor(random_state = 1)
rf_model.fit(x_train,y_train)

RandomForestRegressor(random_state=1)

In [493]:
rf_val_predis = rf_model.predict(x_valid)

In [494]:
rf_val_predis[:5]

array([208467.1 , 148431.  , 113311.39, 228848.18,  91602.  ])

In [495]:
test_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20.0,RH,80.0,11622.0,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5.0,6.0,1961.0,1961.0,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,CBlock,TA,TA,No,Rec,468.0,LwQ,144.0,270.0,882.0,GasA,TA,Y,SBrkr,896.0,0.0,0.0,896.0,0.0,0.0,1.0,0.0,2.0,1.0,TA,5.0,Typ,0.0,NaN,Attchd,1961.0,Unf,1.0,730.0,TA,TA,Y,140.0,0.0,0.0,0.0,120.0,0.0,NaN,MnPrv,NaN,0.0,6.0,2010.0,WD,Normal
1,1462,20.0,RL,81.0,14267.0,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6.0,6.0,1958.0,1958.0,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,108.0,TA,TA,CBlock,TA,TA,No,ALQ,923.0,Unf,0.0,406.0,1329.0,GasA,TA,Y,SBrkr,1329.0,0.0,0.0,1329.0,0.0,0.0,1.0,1.0,3.0,1.0,Gd,6.0,Typ,0.0,NaN,Attchd,1958.0,Unf,1.0,312.0,TA,TA,Y,393.0,36.0,0.0,0.0,0.0,0.0,NaN,NaN,Gar2,12500.0,6.0,2010.0,WD,Normal
2,1463,60.0,RL,74.0,13830.0,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,5.0,5.0,1997.0,1998.0,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,PConc,Gd,TA,No,GLQ,791.0,Unf,0.0,137.0,928.0,GasA,Gd,Y,SBrkr,928.0,701.0,0.0,1629.0,0.0,0.0,2.0,1.0,3.0,1.0,TA,6.0,Typ,1.0,TA,Attchd,1997.0,Fin,2.0,482.0,TA,TA,Y,212.0,34.0,0.0,0.0,0.0,0.0,NaN,MnPrv,NaN,0.0,3.0,2010.0,WD,Normal
3,1464,60.0,RL,78.0,9978.0,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6.0,6.0,1998.0,1998.0,Gable,CompShg,VinylSd,VinylSd,BrkFace,20.0,TA,TA,PConc,TA,TA,No,GLQ,602.0,Unf,0.0,324.0,926.0,GasA,Ex,Y,SBrkr,926.0,678.0,0.0,1604.0,0.0,0.0,2.0,1.0,3.0,1.0,Gd,7.0,Typ,1.0,Gd,Attchd,1998.0,Fin,2.0,470.0,TA,TA,Y,360.0,36.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,6.0,2010.0,WD,Normal
4,1465,120.0,RL,43.0,5005.0,Pave,NaN,IR1,HLS,AllPub,Inside,Gtl,StoneBr,Norm,Norm,TwnhsE,1Story,8.0,5.0,1992.0,1992.0,Gable,CompShg,HdBoard,HdBoard,NaN,0.0,Gd,TA,PConc,Gd,TA,No,ALQ,263.0,Unf,0.0,1017.0,1280.0,GasA,Ex,Y,SBrkr,1280.0,0.0,0.0,1280.0,0.0,0.0,2.0,0.0,2.0,1.0,Gd,5.0,Typ,0.0,NaN,Attchd,1992.0,RFn,2.0,506.0,TA,TA,Y,0.0,82.0,0.0,0.0,144.0,0.0,NaN,NaN,NaN,0.0,1.0,2010.0,WD,Normal

In [516]:
x_test = test_new_df.iloc[:,1:]
test_new_df.shape

(1459, 340)

In [517]:
y_answer = dt_model.predict(x_test)

In [518]:
pd.DataFrame({"Id": test_df["Id"], "SalePrice": y_answer})
#len(test_df["Id"])

        Id  SalePrice
0     1461   129500.0
1     1462   144000.0
2     1463   184000.0
3     1464   216500.0
4     1465   197000.0
...    ...        ...
1454  2915    75500.0
1455  2916    83500.0
1456  2917   109000.0
1457  2918    93500.0
1458  2919   199900.0

[1459 rows x 2 columns]

In [519]:
answer = pd.DataFrame({"Id": test_df["Id"], "SalePrice": y_answer})
answer

        Id  SalePrice
0     1461   129500.0
1     1462   144000.0
2     1463   184000.0
3     1464   216500.0
4     1465   197000.0
...    ...        ...
1454  2915    75500.0
1455  2916    83500.0
1456  2917   109000.0
1457  2918    93500.0
1458  2919   199900.0

[1459 rows x 2 columns]

In [520]:
type(answer)

pandas.core.frame.DataFrame

In [521]:
answer.to_csv("answer_final_2.csv", index = False)